### ISSUE TITLE
streaming output with function call throws exception: No function callback found for function name: 

### ISSUE THREAD

**Issue by hongshuo-wang** [alibaba/spring-ai-alibaba#215]
Function Calling

streaming output with function call throws exception: No function callback found for function name: ,the name of function in toolCalls parameter is empty

you can reproduce this bug with official tutorial sample code, in 1.0.0-M3.2 or 1.0.0-M2.1 version which I've tried.

采用流式输出函数调用结果，会抛异常No function callback found for function name: ，debug发现找不到toolCalls变量里面的function的name，并且之前有一个测试过是正常的代码，现在调用也不正常了，怀疑是百炼平台的流式api接口出了点问题。

**Comment by LittleDrip** [comment]
我也出现了这个问题，openAI的就可以用的，希望尽快解决

**Comment by hongshuo-wang** [comment]
> 我也出现了这个问题，openAI的就可以用的，希望尽快解决

https://github.com/alibaba/spring-ai-alibaba/issues/199#issuecomment-2550006265
This solution works for now, but it's not very convenient as it requires modifying the source code. I hope that the official next version can include this fix as soon as possible. It would be great if it could be urgently addressed since it has a significant impact.

目前采用这个方案解决了，但是要改源码，还是不太方便，希望官方下个版本尽快上，能紧急修复下吧，影响还挺大的

**Comment by lovesupertiger** [comment]
遇到同样的问题,该怎么解决?

**Comment by lovesupertiger** [comment]
谢谢

**Comment by lovesupertiger** [comment]
@PolarishT @Cirilla-zmh 谢谢

**Comment by Cirilla-zmh** [comment]
@hongshuo-wang @lovesupertiger @LittleDrip 
Hey, seems to be a lot of similar questions being asked at the same time. I have fixed this issue based on @PolarishT's PR and hope it could work well. (I could work as expected on my machine now)

**Comment by LittleDrip** [comment]
> @hongshuo-wang @lovesupertiger @LittleDrip Hey, seems to be a lot of similar questions being asked at the same time. I have fixed this issue based on @PolarishT's PR and hope it could work well. (I could work as expected on my machine now)

Why do I still have the above error? Is it because the Taobao image source I am using has not been updated？

**Comment by Cirilla-zmh** [comment]
> Why do I still have the above error? Is it because the Taobao image source I am using has not been updated？

This fix has just been merged into the code repository and is not yet included in latest release. So if you want to verify this fix, you will need to package it locally first.

I anticipate that a new release may be made today or tomorrow. cc @chickenlj

**Comment by hongshuo-wang** [comment]
> @hongshuo-wang @lovesupertiger @LittleDrip Hey, seems to be a lot of similar questions being asked at the same time. I have fixed this issue based on @PolarishT's PR and hope it could work well. (I could work as expected on my machine now)

Thank you very much for your work. I hope this framework will continue to grow stronger. I will keep using it and provide feedback.

**Comment by xs-java2ai** [comment]
> > Why do I still have the above error? Is it because the Taobao image source I am using has not been updated？
> 
> This fix has just been merged into the code repository and is not yet included in latest release. So if you want to verify this fix, you will need to package it locally first.
> 
> I anticipate that a new release may be made today or tomorrow. cc @chickenlj

You said: release a new version today or tomorrow to fix it. Why hasn't it been published?

**Comment by Cirilla-zmh** [comment]
> You said: release a new version today or tomorrow to fix it. Why hasn't it been published?

I apologize for my miscalculation. There may have been some issues that delayed the release. I'm not the release manager so I could not help you. cc @chickenlj

**Comment by Dawn123F** [comment]
应该怎么修改呢

**Comment by bijingliang** [comment]
spring-ai-alibaba-starter 使用1.0.0-M3.3这个版本，这个版本已经处理了这个问题
